[env]
TERM = "xterm-256color"


[general]
import = ["~/.config/alacritty/rosepine.toml"]

[font]
normal = {family ="JetBrainsMono",style="Regular"}
size = 14.5

[colors.primary]
background = "#000000"

[mouse]
hide_when_typing = true

[keyboard]
bindings=[{key="Space",mods="Control",action="ToggleViMode"}]


