[widget.brightness.actions]
scroll_up = "brightness-up 2%"
scroll_down = "brightness-down 2%"

[widget.volume.actions]
scroll_up = "volume-up 2%"
scroll_down = "volume-down 2%"

[widget.network]
show_label = false

[widget.clock]
format = "{:%-I:%M %p} {:%d-%b}"
tooltip_format = "{:%d %B %A %Y}"

