#!/usr/bin/env bash
set -euo pipefail

for dir in "$HOME"/dotfiles/*; do
    basedir=$(basename "$dir")

    case "$basedir" in
        scripts)
            mkdir -p "$HOME/.local/bin"
            cp -r "$dir"/. "$HOME/.local/bin"
            ;;

        zsh)
            echo "creating symlinks for zsh"
            ln -sf "$dir/.zshrc" "$HOME/.zshrc"
            ln -sf "$dir/.zprofile" "$HOME/.zprofile"
            ;;

        keyd)
            sudo install -Dm644 "$dir/default.conf" /etc/keyd/default.conf
            ;;

        *)
            mkdir -p "$HOME/.config/$basedir"
            cp -r "$dir"/. "$HOME/.config/$basedir"
            ;;
    esac
done
