#!/usr/bin/env bash

for dir in "$HOME"/dotfiles/*; do
    basedir=$(basename "$dir")

    case "$basedir" in
        scripts)
            mkdir -p "$HOME/.local/bin"
            ln -sf "$dir"/* "$HOME/.local/bin"
            ;;

        zsh)
            echo "creating symlinks for zsh"
            ln -sf "$dir/.zshrc" "$HOME/.zshrc"
            ln -sf "$dir/.zprofile" "$HOME/.zprofile"
            ;;

        keyd)
            echo "copying keyd config"
            sudo mkdir -p /etc/keyd
            sudo cp "$dir/default.conf" /etc/keyd/default.conf
            ;;

        *)
            mkdir -p "$HOME/.config/$basedir"
            ln -sf "$dir"/* "$HOME/.config/$basedir"
            ;;
    esac
done
