#!/usr/bin/env bash

selected=$(docker ps -a --format "{{.Names}}\t{{.Status}}" | fzf | awk '{print $1}')

if [[ -z $selected ]]; then
    echo "nothing selected"
    exit 0
fi

docker start "$selected"
