#!/usr/bin/env bash

#this script has been yanked from ThePrimeagen
# https://github.com/ThePrimeagen/tmux-sessionizer/tree/master

switch_to() {
    if [[ -z $TMUX ]]; then
        tmux attach-session -t $1
    else
        tmux switch-client -t $1
    fi
}

has_session() {
    tmux list-sessions | grep -q "^$1:"
}


if [[ $# -eq 1 ]]; then
    selected=$1
else

if command -v fd >/dev/null 2>&1; then

  selected=$(fd --type d . --full-path "$HOME" --max-depth 3 \
    --exclude node_modules --exclude .git --exclude venv \
    --exclude __pycache__ --exclude .cache --exclude target \
    --exclude build --exclude vendor --exclude pkg --exclude mod |sed "s|$HOME/||"| fzf)
else
  selected=$(find "$HOME" -maxdepth 3  -type d \
    \( -path '*/node_modules' -o -path '*/.git' -o -path '*/venv' \
       -o -path '*/__pycache__' -o -path '*/.cache' -o -path '*/target' \
       -o -path '*/build' -o -path '*/vendor' -o -path '*/pkg' -o -path '*/mod' \) \
    -prune  -o -type d -print || sed "s|$HOME/||"| fzf)
fi
fi

if [[ -z $selected ]]; then
    exit 0
else
    selected="$HOME/$selected"
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected -d
    # tmux send-keys -t "$selected_name" "nvim ." C-m
    tmux new-window -t "$selected_name" -c "$selected"
    tmux select-window -t "$selected_name":1
    tmux attach-session -t "$selected_name"
    exit 0
fi

if ! has_session $selected_name; then
    tmux new-session -ds $selected_name -c $selected
    # tmux send-keys -t "$selected_name" "nvim ." C-m
    tmux new-window -t "$selected_name" -c "$selected"
    tmux select-window -t "$selected_name":1
fi

switch_to $selected_name
