#!/usr/bin/env bash


TOUCHPAD_NAME_HYPR="elan071a:00-04f3:30fd-touchpad"
OVERRIDE_FILE="/tmp/touchpad_override"

while true; do
    if [ -f "$OVERRIDE_FILE" ]; then
            sleep 5
            continue
    fi

    if hyprctl devices | grep -i "$MOUSE_NAME_HYPR" >/dev/null; then
       hyprctl eval 'hl.device({ name = "elan071a:00-04f3:30fd-touchpad", enabled = false })'
    else
       hyprctl eval 'hl.device({ name = "elan071a:00-04f3:30fd-touchpad", enabled = true })'
    fi
  sleep 5
done

